### ISSUE TITLE
What message should I expect if testing with validateSDKIntegration?

### ISSUE THREAD

**Issue by rockingdice** [RodrigoSMarques/flutter_branch_sdk#3]
I tried with the latest version but no logs in the console. What messages should I expect?

**Comment by RodrigoSMarques** [comment]
Hi @rockingdice 
For iOS:
![Captura de Tela 2020-01-06 às 13 28 05](https://user-images.githubusercontent.com/17687286/71831930-a3cc9280-3088-11ea-8cc2-a7764361caec.png)

![Captura de Tela 2020-01-06 às 13 28 16](https://user-images.githubusercontent.com/17687286/71831947-a9c27380-3088-11ea-97dc-25bc4644e362.png)

For Android, see Logcat:
![Captura de Tela 2020-01-06 às 13 31 45](https://user-images.githubusercontent.com/17687286/71832097-fa39d100-3088-11ea-94cd-f4a2bf5bb25c.png)

**Comment by rockingdice** [comment]
@RodrigoSMarques Thanks!

I found an exception in the logs:
```
   PlatformException(error, Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference, null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
    #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
    <asynchronous suspension>
    #2      FlutterBranchSdk.validateSDKIntegration (package:flutter_branch_sdk/src/branch_sdk.dart:76:21)
    #3      initBranch (package:mhwo/main.dart:191:20)
    #4      mainInit.<anonymous closure> (package:mhwo/main.dart:232:5)
    #5      FlutterBugly.postCatchedException.<anonymous closure> (package:flutter_bugly/src/flutter_bugly.dart:145:15)
    #6      _rootRun (dart:async/zone.dart:1126:13)
    #7      _CustomZone.run (dart:async/zone.dart:1023:19)
    #8      _runZoned (dart:async/zone.dart:1518:10)
    #9      runZoned (dart:async/zone.dart:1502:12)
```

I don't know why. I followed every step from the guide.

**Comment by RodrigoSMarques** [comment]
Very strange.  Has your project been migrated to AndroidX?

**Comment by rockingdice** [comment]
Yes, it's migrated to AndroidX.
My project is not a new one, it's created a long time ago (a year or more). 
I'm now using the beta channel(latest).

**Comment by rockingdice** [comment]
I tried the example project, but I cannot see logcat tab in my IDE

**Comment by RodrigoSMarques** [comment]
> I tried the example project, but I cannot see logcat tab in my IDE

I open a new window in Android Studio with Flutter's Android project. This allows you to view Logcat.

**Comment by RodrigoSMarques** [comment]
> Yes, it's migrated to AndroidX.
> My project is not a new one, it's created a long time ago (a year or more).
> I'm now using the beta channel(latest).

I already know the problem. I am investigating how to solve, but this should solve.
https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

**Comment by RodrigoSMarques** [comment]
Wait, I think I found a solution

**Comment by rockingdice** [comment]
OK, I'll try when I'm free

**Comment by rockingdice** [comment]
Fixed! Thank you! I'll close this issue.

**Comment by quetool** [comment]
Can you post the fix @rockingdice ? I'm having that very issue

**Comment by rockingdice** [comment]
@rockingdice sorry I don't remember it, but from the conversation, I think it's fixed by @RodrigoSMarques 's patch.

**Comment by quetool** [comment]
@rockingdice It is not Cc @RodrigoSMarques  :(
I'm on latest version and still having this issue. Every step in the evaluation succeeds but tho but still crashing with 
```
PlatformException(error, Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference, null)
```
